### ISSUE TITLE
CAMPHOR- Make が使える時間帯を表す Validation を追加する

### ISSUE THREAD

**Issue by KMConner** [camphor-/hanreki#31]
CAMPHOR- Make は CAMPHOR- の会館時間中いつでも使えるわけではないため、別途使える時間を Website などに掲載したい。

この issue ではそのための仕様に関して議論する

## 仕様として考えうるもの

後方互換を考えると、 Column の追加はかなり大変そうなのでしない方針

**1. csv の row はopen と make で分ける**

例えば 4 月 29 日の16時から19時まで開館しており、Make が利用可能な時は以下のような csv になる

e.g.
```csv
29,木,16:00,19:00,Open,,
29,木,16:00,19:00,Make,,
```

**2. make とかけば、開館日で、make が利用可能であることを意味する**

例えば 4 月 29 日の16時から19時まで開館しており、Make が利用可能な時は以下のような csv になる
(i.e. `Open` は書かない)

e.g.
```csv
29,木,16:00,19:00,Make,,
```

**3. open と make は同じ row にして make,open みたいな感じで設定する**

区切り文字に何を使うかは要検討

e.g.
```csv
29,木,16:00,19:00,"Make,Open",,
```

**Comment by KMConner** [comment]
「Make が利用可能な時間帯ならばHOUSE の開館時間」は任意の時刻に関して常に真なので
1 or 2 が良さそう

問題は、同じ日で、開館時間と Make が使える時間が一致しない場合
(e.g. 16-19時の間で開館しているが Make が使えるのは 17-19時である)
を許容するかどうか

**Comment by sanposhiho** [comment]
個人的には開館時間、makeが使える時間が異なることがあるにしろないにしろ、1に+1です
理由はmakeはopenも兼ねるとかややこしい事するより仕様がシンプルだから

(上手く説明出来ないけどopen(開館やってるよ),make(makeやってるよ)の方がひとつの属性にひとつの意味しかないという意味でシンプルで、open(開館やってるよ),make(開館やってるよ+makeやってるよ)だと違和感という感覚です)

**Comment by reo-g** [comment]
僕も1に一票です
開館に加えてやるものとしてmakeは追加のイベントなのでさんぽしくんと同じで受け入れやすいです(?)

**Comment by sanposhiho** [comment]
もともと文字列を許容していたので追加の開発は必要なかった
closed
